<?php

namespace Goodjob\AppBundle\Repository;
use Goodjob\AppBundle\Entity\Application;
use Webron\CoreBundle\Entity\WebronEntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends WebronEntityRepository
{
    public function newApplication($data){
        $application = new Application();
        $application->setName($data['name']);
        $application->setEmail($data['email']);
        $application->setPhone($data['phone']);
        $application->setCourseId($this->getRepo('Course')->getCourseIdByCodeName($data['code_name']));
        $this->_em->persist($application);
        $this->_em->flush();
    }
}
