<?php

namespace Goodjob\AppBundle\Repository;
use Webron\CoreBundle\Entity\WebronEntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends WebronEntityRepository
{
    public function showAll(){
        return $this->findAll();
    }

    public function showOneById($id){
        return $this->find($id);
    }
}
