<?php

namespace Goodjob\AppBundle\Repository;
use Goodjob\AppBundle\Entity\Subscription;
use Webron\CoreBundle\Entity\WebronEntityRepository;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends WebronEntityRepository
{
    public function newSubscription($email){
        $subscribtion = new Subscription();
        $subscribtion->setEmail($email);
        $subscribtion->setDatimeSubscription(new \DateTime());
        $this->_em->persist($subscribtion);
        $this->_em->flush();
        return 1;
    }
}
