parameters:
#    webron_upload.example.class: Webron\UploadBundle\Example

services:
#    webron_upload.example:
#        class: %webron_upload.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
