parameters:
#    webron_pdf.example.class: Webron\PdfBundle\Example

services:
#    webron_pdf.example:
#        class: %webron_pdf.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
