parameters:
#    webron_core.example.class: Webron\CoreBundle\Example

services:
#    webron_core.example:
#        class: %webron_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
