parameters:
#    webron_user.example.class: Sitapa\UserBundle\Example

services:
#    webron_user.example:
#        class: %webron_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
