parameters:
#    webron_tree.example.class: Webron\TreeBundle\Example

services:
#    webron_tree.example:
#        class: %webron_tree.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
