parameters:
#    webron_parser.example.class: Webron\ParserBundle\Example

services:
#    webron_parser.example:
#        class: %webron_parser.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
