parameters:
#    webron_download.example.class: Webron\DownloadBundle\Example

services:
#    webron_download.example:
#        class: %webron_download.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
